## Question 1
Link--> https://www.hackerrank.com/challenges/np-arrays/problem?isFullScreen=false
    

### Solution 

In [3]:
import numpy

def arrays(arr):
     return(numpy.array(arr[::-1], float))
arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 3 76 9 3 -4
[-4.  3.  9. 76.  3.  1.]


## Question 2
Link--> https://www.hackerrank.com/challenges/np-shape-reshape/problem?isFullScreen=true

### Solution 

In [13]:
import numpy
print(numpy.array(str(input()).strip().split(), int).reshape(3,3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Question 3
Link--> https://www.hackerrank.com/challenges/np-transpose-and-flatten/problem?h_r=next-challenge&h_v=zen&isFullScreen=false

### Solution 

In [14]:
import numpy
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for _ in range(n)], int)
print (array.transpose())
print (array.flatten())

2 5 
3 8 
4 9 
[[3 4]
 [8 9]]
[3 8 4 9]


## Question 4
Link--> https://www.hackerrank.com/challenges/np-concatenate/problem?h_r=next-challenge&h_v=zen&isFullScreen=false&h_r=next-challenge&h_v=zen

### Solution 

In [16]:
import numpy as np
a, b, c = map(int,input().split())
arr1 = np.array([input().split() for _ in range(a)],int)
arr2 = np.array([input().split() for _ in range(b)],int)
print(np.concatenate((arr1, arr2), axis = 0))

6 7 8 
1 5 
1 5 
1 5 
1 5 
1 5 
1 5 
1 5 
1 5 
5 1 
5 1 
5 1 
5 1 
5 1 
[[1 5]
 [1 5]
 [1 5]
 [1 5]
 [1 5]
 [1 5]
 [1 5]
 [1 5]
 [5 1]
 [5 1]
 [5 1]
 [5 1]
 [5 1]]


## Question 5
Link--> https://www.hackerrank.com/challenges/np-zeros-and-ones/problem?h_r=next-challenge&h_v=zen&isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 

In [17]:
nums = tuple(map(int, input().split()))
print (numpy.zeros(nums, dtype = numpy.int))
print (numpy.ones(nums, dtype = numpy.int))

5 5 6 
[[[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]

 [[0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]
  [0 0 0 0 0 0]]]
[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


## Question 6
Link--> https://www.hackerrank.com/challenges/np-eye-and-identity/problem?h_r=next-challenge&h_v=zen&isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 

In [18]:
import numpy

numpy.set_printoptions(sign=' ')
print(numpy.eye(*map(int, input().split())))

5 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


## Question 7
Link--> https://www.hackerrank.com/challenges/np-array-mathematics/problem?h_r=next-challenge&h_v=zen&isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 

In [21]:
import numpy

n, m = [int(x) for x in input().strip().split()]

a = numpy.array([[int(x) for x in input().strip().split()] for _ in range(n)])
b = numpy.array([[int(x) for x in input().strip().split()] for _ in range(n)])

print(a + b)
print(a - b)
print(a * b)
print(a // b)
print(a % b)
print(a**b)

3 7 
4 8 0 2 
4 7 89 1
1 0 0 3
1 3 4 8 
1 5 8 3 
0 5 8 3 
[[ 5 11  4 10]
 [ 5 12 97  4]
 [ 1  5  8  6]]
[[ 3  5 -4 -6]
 [ 3  2 81 -2]
 [ 1 -5 -8  0]]
[[  4  24   0  16]
 [  4  35 712   3]
 [  0   0   0   9]]
[[ 4  2  0  0]
 [ 4  1 11  0]
 [ 0  0  0  1]]
[[0 2 0 2]
 [0 2 1 1]
 [0 0 0 0]]
[[          4         512           0         256]
 [          4       16807 -2124152383           1]
 [          1           0           0          27]]


<ipython-input-21-c83882e3c750>:11: RuntimeWarning: divide by zero encountered in floor_divide
  print(a // b)
<ipython-input-21-c83882e3c750>:12: RuntimeWarning: divide by zero encountered in remainder
  print(a % b)


## Question 8
Link--> https://www.hackerrank.com/challenges/floor-ceil-and-rint/problem?h_r=next-challenge&h_v=zen&isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 

In [22]:
import numpy

numpy.set_printoptions(sign=' ')

array = numpy.array(input().split(),float)

print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


## Question 9
Link--> https://www.hackerrank.com/challenges/np-sum-and-prod/problem?h_r=next-challenge&h_v=zen&isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution

In [23]:
import numpy

N, M = map(int, input().split())
A = numpy.array([input().split() for _ in range(N)], int)
print(numpy.prod(numpy.sum(A, axis=0), axis=0))

5 8 
3 8 
4 8 
2 0 
4 8 
8 3 
567


## Question 10 
Link--> https://www.hackerrank.com/challenges/np-min-and-max/problem?h_r=next-challenge&h_v=zen&isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 


In [ ]:
import numpy as np

n, m = [int(x) for x in input().strip().split()]
array = np.array([[int(x) for x in input().strip().split()] for _ in range(n)])
print(np.max(np.min(array, axis = 1)))

5 9 
2 6 
7 0 


## Question 11
Link--> https://www.hackerrank.com/challenges/np-mean-var-and-std/problem?isFullScreen=false

### Solution 

In [1]:
import numpy as np 

n,m = map(int, input().split())
b = []
for i in range(n):
    a = list(map(int, input().split()))
    b.append(a)

b = np.array(b)

np.set_printoptions(legacy='1.13')
print(np.mean(b, axis = 1))
print(np.var(b, axis = 0))
print(np.std(b))

2 2 
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


## Question 12
Link--> https://www.hackerrank.com/challenges/np-dot-and-cross/problem?isFullScreen=false

### Solution 

In [8]:
import numpy

n = int(input())
a = numpy.array([input().split() for _ in range(n)], int)
b = numpy.array([input().split() for _ in range(n)], int)
print(numpy.dot(a, b))


2 
1 2 
3 4 
4 5
6 7 
[[16 19]
 [36 43]]


## Question 13
Link--> https://www.hackerrank.com/challenges/np-inner-and-outer/problem?isFullScreen=false&h_r=next-challenge&h_v=zen

### Solution 

In [9]:
import numpy as np
A = np.array(input().split(), int)
B = np.array(input().split(), int)
print(np.inner(A,B), np.outer(A,B), sep='\n')

1 6 
5 9 
59
[[ 5  9]
 [30 54]]


## Question 14
Link-->https://www.hackerrank.com/challenges/np-polynomials/problem?isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 

In [10]:
import numpy as np

poly = [float(x) for x in input().split()]
x = float(input())
print(np.polyval(poly, x))

2.2 4 7
6
110.2


## Question 15
Link--> https://www.hackerrank.com/challenges/np-linear-algebra/problem?isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 

In [11]:
import numpy as np

np.set_printoptions(legacy='1.13')

n = int(input())
array = np.array([input().split() for _ in range(n)], float)
print(np.linalg.det(array))

2
1.1 5.6
4.7 8.0
-17.52


## Question 16
Link-->https://www.hackerrank.com/challenges/iterables-and-iterators/problem?isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 

In [12]:
from itertools import combinations

N = int(input())
L = input().split()
K = int(input())

C = list(combinations(L, K))
F = filter(lambda c: 'a' in c, C)
print("{0:.3}".format(len(list(F))/len(C)))

3
a g e
2
0.667


## Question 17
Link-->https://www.hackerrank.com/challenges/maximize-it/problem?isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 

In [13]:
from itertools import product
K,M = map(int,input().split())
nums = []
for _ in range(K):
    row = map(int,input().split()[1:])
    nums.append(map(lambda x:x**2%M, row))
print(max(map(lambda x: sum(x)%M, product(*nums))))

3 1333
2 5 9 
3 7 5 9
5 2 7 9 1 0 
243


## Question 18
Link--> https://www.hackerrank.com/challenges/words-score/problem?isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 

In [14]:
def is_vowel(letter):
    return letter in ['a', 'e', 'i', 'o', 'u', 'y']


def score_words(words):
    score = 0
    for word in words:
        num_vowels = 0
        for letter in word:
            if is_vowel(letter):
                num_vowels += 1
        if num_vowels % 2 == 0:
            score += 2
        else:
            score += 1
    return score



n = int(input())
words = input().split()
print(score_words(words))

5 
hello joey
3


## Question 19
Link--> https://www.hackerrank.com/challenges/default-arguments/problem?isFullScreen=false&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen&h_r=next-challenge&h_v=zen

### Solution 

In [16]:
class EvenStream(object):
    def __init__(self):
        self.current = 0

    def get_next(self):
        to_return = self.current
        self.current += 2
        return to_return

class OddStream(object):
    def __init__(self):
        self.current = 1

    def get_next(self):
        to_return = self.current
        self.current += 2
        return to_return
def print_from_stream(n, stream=EvenStream()):
    for _ in range(n):
        print(stream.get_next())


queries = int(input())
for _ in range(queries):
    stream_name, n = input().split()
    n = int(n)
    if stream_name == "even":
        print_from_stream(n)
    else:
        print_from_stream(n, OddStream())

4
odd 2
1
3
even 3
0
2
4
odd 1
1
even 6
6
8
10
12
14
16
